---

- name: Check Web Console Certificates
  shell: |
      echo | openssl s_client -servername "{{ web_console }}" -connect "{{ web_console }}:443" 2>/dev/null | openssl x509 -noout -dates
  register: web_console_ssl

- name: Extract start and end dates
  set_fact:
    cert_start_date: "{{ web_console_ssl.stdout | regex_search('notBefore=(.*)', '\\1') }}"
    cert_end_date: "{{ web_console_ssl.stdout | regex_search('notAfter=(.*)', '\\1') }}"

- name: Display certificate information with semicolon separator
  debug:
    msg: |
      Address;Start Date;End Date
      {{web_console}};{{ cert_start_date }};{{ cert_end_date }}
          
- name: APP_UI Certificates
  when: app_ui is not none
  block:
    - name: Check App UI Certificates
      shell: |
          echo | openssl s_client -servername "{{ app_ui }}" -connect "{{ app_ui }}:443" 2>/dev/null | openssl x509 -noout -dates
      register: app_ui_ssl

    - name: Extract start and end dates for app_ui
      set_fact:
        app_ui_cert_start_date: "{{ app_ui_ssl.stdout | regex_search('notBefore=(.*)', '\\1') }}"
        app_ui_cert_end_date: "{{ app_ui_ssl.stdout | regex_search('notAfter=(.*)', '\\1') }}"

    - name: Display App UI certificate information
      debug:
        msg: |
          Address;Start Date;End Date
          {{ app_ui }};{{ app_ui_cert_start_date }};{{ app_ui_cert_end_date }}

#- name: Debug Deployments
#  debug:
#    msg: "{{ web_console_ssl.stdout }}"